version: '3.8'

services:
  
  db:
    image: postgres:15-alpine
    container_name: shortener-db
    environment:
      POSTGRES_USER: myuser     
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: linkdb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  
  redis:
    image: redis:alpine
    container_name: shortener-redis
    ports:
      - "6379:6379"

  
  app:
    build: .
    container_name: shortener-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      
      
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/linkdb
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

volumes:
  postgres_data: